.TH "asamba.insert_def.insertion" 3 "Mon May 15 2017" "ASAMBA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asamba.insert_def.insertion
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, table)"
.br
.ti -1c
.RI "def \fBset_table\fP (self, table)"
.br
.ti -1c
.RI "def \fBget_table\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Inserting data into the database tables

.fi
.PP
 
.PP
Definition at line 9 of file insert_def\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def asamba\&.insert_def\&.insertion\&.__init__ ( self,  table)"

.PP
.nf
class constructor 

@param table: (default=None); insert data into one of the tables defined in the schema of the 
   database (grid.sql). The allowed values are:
   - tracks
   - models
   - rotation_rates
   - mode_types
   - modes
@type table: string

.fi
.PP
 
.PP
Definition at line 15 of file insert_def\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASAMBA from the source code\&.
