.TH "asamba.var_def.model" 3 "Mon May 15 2017" "ASAMBA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asamba.var_def.model
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fB__enter__\fP (self)"
.br
.ti -1c
.RI "def \fB__exit__\fP (self, type, value, traceback)"
.br
.ti -1c
.RI "def \fBset_filename\fP (self, filename)"
.br
.ti -1c
.RI "def \fBset_by_dic\fP (self, dic)"
.br
.ti -1c
.RI "def \fBset\fP (self, attr, val)"
.br
.ti -1c
.RI "def \fBget\fP (self, attr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBM_ini\fP"
.br
.ti -1c
.RI "\fBfov\fP"
.br
.ti -1c
.RI "\fBZ\fP"
.br
.ti -1c
.RI "\fBlogD\fP"
.br
.ti -1c
.RI "\fBXc\fP"
.br
.ti -1c
.RI "\fBmodel_number\fP"
.br
.ti -1c
.RI "\fBstar_mass\fP"
.br
.ti -1c
.RI "\fBradius\fP"
.br
.ti -1c
.RI "\fBlog_Teff\fP"
.br
.ti -1c
.RI "\fBlog_g\fP"
.br
.ti -1c
.RI "\fBlog_L\fP"
.br
.ti -1c
.RI "\fBlog_Ledd\fP"
.br
.ti -1c
.RI "\fBlog_abs_mdot\fP"
.br
.ti -1c
.RI "\fBmass_conv_core\fP"
.br
.ti -1c
.RI "\fBstar_age\fP"
.br
.ti -1c
.RI "\fBdynamic_timescale\fP"
.br
.ti -1c
.RI "\fBkh_timescale\fP"
.br
.ti -1c
.RI "\fBnuc_timescale\fP"
.br
.ti -1c
.RI "\fBlog_center_T\fP"
.br
.ti -1c
.RI "\fBlog_center_Rho\fP"
.br
.ti -1c
.RI "\fBlog_center_P\fP"
.br
.ti -1c
.RI "\fBcenter_h1\fP"
.br
.ti -1c
.RI "\fBcenter_h2\fP"
.br
.ti -1c
.RI "\fBcenter_he3\fP"
.br
.ti -1c
.RI "\fBcenter_he4\fP"
.br
.ti -1c
.RI "\fBcenter_c12\fP"
.br
.ti -1c
.RI "\fBcenter_c13\fP"
.br
.ti -1c
.RI "\fBcenter_n14\fP"
.br
.ti -1c
.RI "\fBcenter_n15\fP"
.br
.ti -1c
.RI "\fBcenter_o16\fP"
.br
.ti -1c
.RI "\fBcenter_o18\fP"
.br
.ti -1c
.RI "\fBcenter_ne20\fP"
.br
.ti -1c
.RI "\fBcenter_ne22\fP"
.br
.ti -1c
.RI "\fBcenter_mg24\fP"
.br
.ti -1c
.RI "\fBsurface_h1\fP"
.br
.ti -1c
.RI "\fBsurface_h2\fP"
.br
.ti -1c
.RI "\fBsurface_he3\fP"
.br
.ti -1c
.RI "\fBsurface_he4\fP"
.br
.ti -1c
.RI "\fBsurface_c12\fP"
.br
.ti -1c
.RI "\fBsurface_c13\fP"
.br
.ti -1c
.RI "\fBsurface_n14\fP"
.br
.ti -1c
.RI "\fBsurface_n15\fP"
.br
.ti -1c
.RI "\fBsurface_o16\fP"
.br
.ti -1c
.RI "\fBsurface_o18\fP"
.br
.ti -1c
.RI "\fBsurface_ne20\fP"
.br
.ti -1c
.RI "\fBsurface_ne22\fP"
.br
.ti -1c
.RI "\fBsurface_mg24\fP"
.br
.ti -1c
.RI "\fBdelta_nu\fP"
.br
.ti -1c
.RI "\fBnu_max\fP"
.br
.ti -1c
.RI "\fBacoustic_cutoff\fP"
.br
.ti -1c
.RI "\fBdelta_Pg\fP"
.br
.ti -1c
.RI "\fBMbol\fP"
.br
.ti -1c
.RI "\fBbcv\fP"
.br
.ti -1c
.RI "\fBU_B\fP"
.br
.ti -1c
.RI "\fBB_V\fP"
.br
.ti -1c
.RI "\fBV_R\fP"
.br
.ti -1c
.RI "\fBV_I\fP"
.br
.ti -1c
.RI "\fBV_K\fP"
.br
.ti -1c
.RI "\fBR_I\fP"
.br
.ti -1c
.RI "\fBI_K\fP"
.br
.ti -1c
.RI "\fBJ_H\fP"
.br
.ti -1c
.RI "\fBH_K\fP"
.br
.ti -1c
.RI "\fBK_L\fP"
.br
.ti -1c
.RI "\fBJ_K\fP"
.br
.ti -1c
.RI "\fBJ_L\fP"
.br
.ti -1c
.RI "\fBJ_Lp\fP"
.br
.ti -1c
.RI "\fBK_M\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The class that encapsulates the properties of each of MESA output model files which serve as inputs
to GYRE.

.fi
.PP
 
.PP
Definition at line 298 of file var_def\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def asamba\&.var_def\&.model\&.__init__ ( self)"

.PP
.nf
constructor of the class

.fi
.PP
 
.PP
Definition at line 303 of file var_def\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def asamba\&.var_def\&.model\&.get ( self,  attr)"

.PP
.nf
General-purpose method to get the value of a canonical attribute of the object
E.g.

>>>val = a_model.get('age')

@param attr: the name of the available attribute of the class
@type attr: string
@return: the value of the attribute
@rtype: float

.fi
.PP
 
.PP
Definition at line 445 of file var_def\&.py\&.
.SS "def asamba\&.var_def\&.model\&.set ( self,  attr,  val)"

.PP
.nf
Set the value of the specific attribute "attr" of the model object

.fi
.PP
 
.PP
Definition at line 433 of file var_def\&.py\&.
.SS "def asamba\&.var_def\&.model\&.set_by_dic ( self,  dic)"

.PP
.nf
Since the "model" class has many attributes, instead of writing a setter for all 
attributes manually (exhaustive), we pass the attribute values through a dictionary.
This is a general-purpose interface to set the "canonical" attributes of the "model"
class. E.g. 

>>> a_model.set_by_dic({'Teff':10125.0, 'log_g':4.128, 'center_018':1.4509e-5})

@param self: an instance of the model class
@type self: object
@param dic: a dictionary containing the attributes to be set in the model, e.g.
@type dic: dict

.fi
.PP
 
.PP
Definition at line 404 of file var_def\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASAMBA from the source code\&.
