.TH "asamba.var_def" 3 "Mon May 15 2017" "ASAMBA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asamba.var_def
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmodel\fP"
.br
.ti -1c
.RI "class \fBmodels\fP"
.br
.ti -1c
.RI "class \fBmodes\fP"
.br
.ti -1c
.RI "class \fBtrack\fP"
.br
.ti -1c
.RI "class \fBtracks\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This module provides the track and tracks class objects and some basic functionalities. The "tracks"
is build based on the "track" object.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ASAMBA from the source code\&.
