.TH "asamba.artificial_neural_network" 3 "Mon May 15 2017" "ASAMBA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asamba.artificial_neural_network
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBneural_net\fP"
.br
.RI "
.SS ""
.PP
.SH ""
.PP
.PP
.SH ""
.PP
.PP
.SH ""
.PP
.PP
.SH ""
.PP
.PP
.SH ""
.PP
.PP
.SS ""
"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "int \fBis_py3x\fP = 3"
.br
.ti -1c
.RI "\fBlog_Teff_err_lower\fP"
.br
.ti -1c
.RI "\fBlog_Teff_err_upper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This module provides various functionalities for carrying out Artificial Neural Network (ANN)
analysis (modelling) using the asteroseismic database, and a given set of observations. This
module builds heavily on the "sampler" module.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ASAMBA from the source code\&.
